#                Key Points
# input()
# int()
# float()
# eval()
# a=int(input("Enter the value:- "))
# b=int(input("Enter the value:- "))
# print(a+b)
# c=float(input("Enter the value:- "))
# d=float(input("Enter the value:- "))
# print(c+d)
# e=eval(input("Enter the value:- "))
# f=eval(input("Enter the value:- "))
# print(e+f)